name: Build
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout patches repo
        uses: actions/checkout@v4
        with:
          path: patches

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::808766853717:role/GitHubActions
          aws-region: us-east-2

      - name: Download source
        run: aws s3 cp $env:SOURCE .\source.zip
        env:
          SOURCE: ${{ secrets.SOURCE_ARCHIVE }}

      - name: Download build toolkit
        run: aws s3 cp $env:SOURCE .\toolkit.zip
        env:
          SOURCE: ${{ secrets.TOOLKIT_ARCHIVE }}

      - name: Extract source
        run: Expand-Archive -Path .\source.zip

      - name: Extract toolkit
        run: Expand-Archive -Path .\toolkit.zip

      - name: Copy gitignore to source
        run: Copy-Item patches\gitignore source\.gitignore

      - name: Apply patches
        run: |
          git init
          git add .
          git commit -m 'Initial directory'
          git am $env:PATCH_DIRECTORY\*.patch
        working-directory: source
        env:
          PATCH_DIRECTORY: ${{ github.workspace }}/patches
