name: Build
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout patches repo
        uses: actions/checkout@v4
        with:
          path: patches

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::808766853717:role/GitHubActions
          aws-region: us-east-2

      - name: Download source
        run: aws s3 cp $env:SOURCE .\source.zip
        env:
          SOURCE: ${{ secrets.SOURCE_ARCHIVE }}

      - name: Download build toolkit
        run: aws s3 cp $env:SOURCE .\toolkit.zip
        env:
          SOURCE: ${{ secrets.TOOLKIT_ARCHIVE }}

      - name: Extract source
        run: Expand-Archive -Path .\source.zip

      - name: Extract toolkit
        run: Expand-Archive -Path .\toolkit.zip

      - name: Copy gitignore to source
        run: Copy-Item patches\gitignore source\.gitignore

      - name: Apply patches
        run: |
          git config --global user.name "actions"
          git config --global user.email "actions@alde.dev"
          git init
          git add .
          git commit -q -m 'Initial commit'
          git am ..\patches\*.patch
        working-directory: source

      - name: Run build
        run: |
          . $env:TOOLKIT\UT2BuildToolkit\activate.ps1
          meson setup build/release -Db_vscrt=none --buildtype release --prefix $env:PREFIX
          ninja -C build/release
        working-directory: source
        env:
          TOOLKIT: ${{ github.workspace }}\toolkit
          PREFIX: ${{ github.workspace }}\source
